name: Release

on:
  push:
    branches: ["CHANGE_HERE_TO_DEPLOY"]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: |
          npm set progress=false
          npm set package-lock=false
          npm set registry https://registry.npmjs.org/ && echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN_PUBLISH }}" > .npmrc
      - run: yarn install --silent --frozen-lockfile
      - run: yarn workspaces run build
      - run: yarn workspaces run npx --no-install semantic-release -e semantic-release-monorepo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN_PUBLISH}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN_PUBLISH}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
